# Generated by Django 3.1.3 on 2020-12-04 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companys', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('github', models.URLField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True, max_length=254)),
                ('portfolio_site', models.URLField(blank=True, max_length=254)),
                ('resume', models.FileField(upload_to='resume/')),
                ('voice', models.FileField(upload_to='audio/')),
                ('message', models.TextField(max_length=254)),
                ('message_html', models.TextField(editable=False)),
                ('audio_duration', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('confidence', models.TextField(blank=True)),
                ('text_sentiment', models.TextField(blank=True,default="0")),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='companys.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
