# Generated by Django 3.1.3 on 2020-12-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Company',
            new_name='company',
        ),
        migrations.AddField(
            model_name='application',
            name='message_html',
            field=models.TextField(default='0', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='github',
            field=models.URLField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='linkedin',
            field=models.URLField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='portfolio_site',
            field=models.URLField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='resume'),
        ),
        migrations.AlterField(
            model_name='application',
            name='voice',
            field=models.FileField(upload_to='voice'),
        ),
    ]
