# Generated by Django 3.1.3 on 2020-12-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='text_sentiment',
            field=models.TextField(blank=True),
        ),
    ]
