# Generated by Django 3.1.3 on 2020-12-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20201204_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='text_sentiment',
            new_name='text_sentiment_score',
        ),
        migrations.AddField(
            model_name='application',
            name='text_sentiment_type',
            field=models.TextField(blank=True),
        ),
    ]
