# Generated by Django 3.1.3 on 2020-12-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20201201_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.TextField(default='0', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='voice',
            field=models.FileField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
