# Generated by Django 3.1.3 on 2020-12-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20201203_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='resume'),
        ),
        migrations.AlterField(
            model_name='application',
            name='voice',
            field=models.FileField(upload_to='audio'),
        ),
    ]
