# Generated by Django 3.1.3 on 2020-12-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20201203_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='voice',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
