# Generated by Django 3.1.3 on 2020-12-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20201203_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['email']},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
    ]
